name: CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@main
    - run: npm install && npm run build
    
      # 部署到 GitHub Pages
    - name: Vue to Github Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        # 这里的 ACCESS_TOKEN 名字需要和下文中的相对应
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        # 打包后的文件部署到哪个分支上
        BRANCH: gh-pages
        # 打包后的文件在哪里
        FOLDER: docs/dist